app_proj/urls.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
PROJECT/URLS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

from django.conf.urls import include, url
from django.contrib import admin
import allauth.account.views as AV

import common.views as BV 
import football.views as FV 
import members.views as MV 
import prediction.views as PV 
import central.views as CV


football_url = [
    url(r'^game_ref/$', FV.fb_game, name='fb_game'),
    url(r'^season_ref/$', FV.fb_season, name='fb_season'),
    url(r'^club_ref/$', FV.fb_club, name='fb_club'),
    url(r'^player_ref/$', FV.fb_player, name='fb_player'),
    url(r'^research_jx/([a-zA-Z0-9_]+)/$', FV.research_jx, name='research_jx'),
    
    url(r'^etl_iplstats/$', FV.etl_iplstats, name='etl_iplstats'),
    url(r'^etl_iplstats_jx/([a-zA-Z0-9_]+)/$', FV.etl_iplstats_jx, name='etl_iplstats_jx'),
    
    url(r'^etl_livescores/$', FV.etl_livescores, name='etl_livescores'),
    url(r'^etl_livescores_jx/([a-zA-Z0-9_]+)/$', FV.etl_livescores_jx, name='etl_livescores_jx'),
    
    url(r'^dataManager_jx/([a-zA-Z0-9_]+)/$', FV.dataManager_jx, name='dataManager_jx'),
]


members_url = [    
    url(r"^accounts/signup/$", AV.signup, name="account_signup"),        # must preserve allauth name field for its internal calls
    url(r"^accounts/login/$", AV.login, name="account_login"),
    url(r"^accounts/logout/$", AV.logout, name="account_logout"),
    
    url(r"^accounts/email/$", MV.email, name="account_email"),
    url(r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", AV.confirm_email, name="account_confirm_email"),
    url(r"^accounts/confirm-email/$", AV.email_verification_sent, name="account_email_verification_sent"),    # used when email still requires confirmation
    url(r"^accounts/password/change/$", AV.password_change, name="account_change_password"),
    url(r"^accounts/password/reset/$", MV.password_reset, name="account_reset_password"),
    url(r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MV.password_reset_from_key, name="account_reset_password_from_key"),
    url(r"^accounts/inactive/$", AV.account_inactive, name="account_inactive"),        
    
    url(r'^auth_dialog/', MV.dialog),
    url(r'^messages/', MV.messages, name='messages'),
    url(r'^members_admin/', MV.members_admin, name='members_admin'),
    url(r'^contacts/', MV.contacts, name='contacts'),
    url(r'^profile/', MV.profile, name='profile'),
    
    url(r'^db_edit/([a-zA-Z0-9_]+)/$', MV.db_edit),
    url(r'^db_report/([a-zA-Z0-9_]+)/$', MV.db_report),
]


central_url = [
    url(r'^store/$', CV.store, name='store'),
    url(r'^company/$', CV.company, name='company'),
    url(r'^data_master/$', CV.master, name='master'),
    url(r'^view_profile/([a-zA-Z0-9_]+)', CV.view_profile, name='view_profile'),
    url(r'^central_jx/([a-zA-Z0-9_]+)/$', CV.central_jx, name='central_jx'),
    
    url(r'^admin_messages/', CV.admin_messages, name='admin_messages'),
    url(r'^adminMsg_jx/([a-zA-Z0-9_]+)/$', CV.adminMsg_jx, name='adminMsg_jx'),
    
    url(r'^pu_rewards/', CV.pu_rewards, name='pu_rewards'),
    url(r'^pu_rewards_jx/([a-zA-Z0-9_]+)/$', CV.pu_rewards_jx, name='pu_rewards_jx'),
    url(r'^pu_message_test/', CV.pu_message_test, name='pu_message_test'),
    
    url(r'^bot_users/', CV.botUsers, name='botUsers'),
    url(r'^botUsers_jx/([a-zA-Z0-9_]+)/$', CV.botUsers_jx, name='botUsers_jx'),
]


univpred_url = [
    url(r'^universal/upgrades/$', PV.univ_headq, name='univ_headq'),
    url(r'^universal/predictions/$', PV.univ_preds, name='univ_preds'),
    url(r'^universal/standings/$', PV.univ_ranks, name='univ_ranks'),
    url(r'^universal/the_rules/$', PV.univ_rules, name='univ_rules'),
    url(r'^universal_jx/([a-zA-Z0-9_]+)/$', PV.universal_jx, name="universal_jx"),
]


urlpatterns = [
    url(r'^$', CV.landing, name='landing_page'),   
    url(r'^members/', include(members_url)),     # do not use a namespace, breaks allauth reverse urls 
    url(r'^research/', include(football_url, namespace='football')),
    url(r'^prediction/', include(univpred_url, namespace='prediction')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^central/', include(central_url, namespace='central', app_name='central')),       # appname?
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    
    url(r'^', BV.not_found, name='not_found'),
]

football/forms.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
FOOTBALL/FORMS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

from django import forms

class DropDownForm(forms.Form):
    drop_down = forms.ChoiceField()

football/views.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
FOOTBALL/VIEWS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

import json
from random import randint

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import user_passes_test

import common.utility as CU
import football.models.tables as FT
import football.models.football as FM
import football.models.dataManager as FD
import football.models.etl_iplstats as FI
import football.models.etl_livescores as FL

import logging
prog_lg = logging.getLogger('progress')
excp_lg = logging.getLogger('exception')


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
REFERENCE PAGES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


def fb_season(request):
    seasons = FM.Reports_General.GetSeasons()
    bk = FM.TimeMachine.GetLastBracket()
    ranks_ft = FM.Reports_Season.GetClubRanksFT(bk['season'])
    rounds = FM.Reports_General.GetRounds(bk['season'], 'today')
    
    lastRnd = rounds[0]   if len(rounds) > 0   else None
    fixture_ft = FM.Reports_Season.GetFixtureFT(bk['season'], lastRnd)
    
    clubs = FM.Reports_General.GetClubs(bk['season'])
    club1_ft = FM.Reports_Season.GetClubGamesFT(bk['season'], clubs[0])
    club2_ft = FM.Reports_Season.GetClubGamesFT(bk['season'], clubs[1])
    
    context = {
        'seasons': seasons,
        'cSeason': bk['season'],
        'clubRanking': mark_safe(json.dumps(ranks_ft)),
        'rounds': rounds,
        'fixture': mark_safe(json.dumps(fixture_ft)),
        'clubs': clubs,
        'club1': mark_safe(json.dumps(club1_ft)),
        'club2': mark_safe(json.dumps(club2_ft)),
    }
    return render(request, 'fb_season.html', context)


def fb_game(request):
    seasons = FM.Reports_General.GetSeasons()
    bk = FM.TimeMachine.GetLastBracket()
    rounds = FM.Reports_General.GetRounds(bk['season'], 'today')
    lastRnd = rounds[0]   if len(rounds) > 0   else None
    
    game_mdls = FT.Game.objects.filter(SeasonFK__Season=bk['season'], Round=lastRnd).order_by('PlayDate')
    lastGame = None
    prevGame = game_mdls[0]
    for game_m in game_mdls:
        if game_m.GoalsHome == None:
            lastGame = prevGame
            break
        prevGame = game_m
    if not lastGame:
        lastGame = prevGame
    
    lastClub = lastGame.ClubHomeFK.Club   if lastGame   else None
    fixture_ft = FM.Reports_Season.GetFixtureFT(bk['season'], lastRnd)
    props_ref = FM.Reports_Game.RunGameProperties(bk['season'], lastRnd, lastClub)
    
    context = {
        'seasons': seasons,
        'cSeason': bk['season'],
        'rounds': rounds,
        'fixture': mark_safe(json.dumps(fixture_ft)),
        'gameProps': mark_safe(json.dumps(props_ref.results)),
    }
    return render(request, 'fb_game.html', context)


def fb_club(request):
    return render(request, 'fb_club.html')


def fb_player(request):
    return render(request, 'fb_player.html')


def research_jx(request, command):
    
    prog_lg.info("ajax command: " + command)
    
    
    if command == 'seasons':
        items = FM.Reports_General.GetSeasons()
        return JsonResponse(items, safe=False)

    elif command == 'clubs':
        season = request.GET.get('season')
        items = FM.Reports_General.GetClubs(season)
        return JsonResponse(items, safe=False)
    
    elif command == 'rounds':
        season = request.GET.get('season')
        filterv = request.GET.get('filter')
        items = FM.Reports_General.GetRounds(season, filterv)
        return JsonResponse(items, safe=False)
    
    elif command == 'players':
        club = request.GET.get('club')
        position = request.GET.get('position')
        items = FM.Reports_General.GetPlayers(club, position)
        return JsonResponse(items, safe=False)
    
    elif command == 'positions':
        items = FM.Reports_General.GetPositions()
        return JsonResponse(items, safe=False)
    
    
    elif command == 'season_data':
        season = request.GET.get('season')  
        ranks_ft = FM.Reports_Season.GetClubRanksFT(season)
        rounds = FM.Reports_General.GetRounds(season, 'lastData')
        roundv = rounds[0]   if rounds   else None
        fixture_ft = FM.Reports_Season.GetFixtureFT(season, roundv)
        clubs = FM.Reports_General.GetClubs(season)
        club1_ft = FM.Reports_Season.GetClubGamesFT(season, clubs[0])
        club2_ft = FM.Reports_Season.GetClubGamesFT(season, clubs[1])
        
        results = {
            'clubRanking': ranks_ft,
            'rounds': rounds,
            'fixture': fixture_ft,
            'clubs': clubs,
            'club1': club1_ft,
            'club2': club2_ft,
        }
        return JsonResponse(results, safe=False)
    
    elif command == 'round_fixture':
        season = request.GET.get('season')
        gameRound = request.GET.get('round')
        ftable = FM.Reports_Season.GetFixtureFT(season, gameRound)
        return JsonResponse(ftable, safe=False)
    
    elif command == 'club_games':
        season = request.GET.get('season')
        club = request.GET.get('club')
        ftable = FM.Reports_Season.GetClubGamesFT(season, club)
        return JsonResponse(ftable, safe=False)
    
    
    elif command == 'season_refresh':
        season = request.GET.get('season')
        rounds = FM.Reports_General.GetRounds(season, 'lastData')
        roundv = rounds[0]   if rounds   else None
        
        fixture_ft = FM.Reports_Season.GetFixtureFT(season, roundv)
        firstClub = fixture_ft['data'][0]['home_club']   if not isinstance(fixture_ft, str)   else None
        props_ref = FM.Reports_Game.RunGameProperties(season, roundv, firstClub)
        
        results = {
            'rounds': rounds,
            'fixture': fixture_ft,
            'home': props_ref.results['home']   if not isinstance(props_ref.results, str)   else None,
            'away': props_ref.results['away']   if not isinstance(props_ref.results, str)   else None,
        }
        return JsonResponse(results, safe=False)
    
    elif command == 'round_game':
        season = request.GET.get('season')
        roundv = request.GET.get('round')
        
        fixture_ft = FM.Reports_Season.GetFixtureFT(season, roundv)
        firstClub = fixture_ft['data'][0]['home_club']   if not isinstance(fixture_ft, str)   else None
        props_ref = FM.Reports_Game.RunGameProperties(season, roundv, firstClub)
        
        results = {
            'fixture': fixture_ft,
            'home': props_ref.results['home'],
            'away': props_ref.results['away'],
        }
        return JsonResponse(results, safe=False)
    
    elif command == 'game_properties':
        season = request.GET.get('season')
        round_ = request.GET.get('round')
        home_club = request.GET.get('home_club')
        hret = FM.Reports_Game.RunGameProperties(season, round_, home_club)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    
    elif command == 'club_props':
        club = request.GET.get('club')
        hret = FM.Reports_Club.GetClubProperties(club)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'players_ingame':
        club = request.GET.get('club')
        season = request.GET.get('season')
        position = request.GET.get('position')
        hret = FM.Reports_Club.GetPlayersInGame(club, season, position)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'player_properties':
        player = request.GET.get('player')
        hret = CU.HttpReturn()
        hret.results = {
            'props': FM.Reports_Player.GetPropertiesDict(player),
            'record': FM.Reports_Player.GetClubRecordDict(player),
        }
        hret.status = 201
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    
    msg = "command invalid: " + command
    return JsonResponse(msg, status = 404)  


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
DATA MANAGEMENT
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


@user_passes_test(lambda u: u.is_superuser)
def dataManager_jx(request, command):
    
    prog_lg.info("ajax command: " + command)
    
    
    if command == 'load_core':
        hret = FD.Manager.LoadCoreFiles()
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'reset':
        hret = FD.Manager.ResetCoreTables()
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'exp_season':
        season = request.GET.get('season')
        FD.Exporter.ExportPlayers(season)
        FD.Exporter.ExportGames(season)
        FD.Exporter.ExportEvents(season)
        
        hret = CU.HttpReturn()
        hret.results = "Export successfull."
        hret.status = 200                
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'imp_season':
        season = request.POST.get('season')
        FD.Importer.ImportPlayers(season)
        FD.Importer.ImportGames(season)
        FD.Importer.ImportEvents(season)
        
        hretRounds = FM.Reports_Admin.GetRoundSummary(season)
        results = {
            'seasonSummary': FM.Reports_Admin.GetSeasonSummary(),
            'byRound': hretRounds.results,
        }
        
        hret = CU.HttpReturn()
        hret.results = results
        hret.status = 200                
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'imp_players':
        season = request.POST.get('season')
        hret = FD.Importer.ImportPlayers(season)
        
        if hret.status >= 400:

football/templates/etl_livescores.html
{% extends "common_base.html" %}
{% load utility_ttags %}

{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_admin">
            <span class="font_title">ETL LiveScores</span>
        </div>
    </div>
</div>


<div id="import_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_admin" style="margin-right: 0px;">
                        <span class="font_section">Web Import</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_admin format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "import" %}</div>
    </div>
    
    <div class="col-xs-12 ">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_strong "cfg" "Import Config" %}
            <div class="display_block">
                {% ctrl_select "season" "Season" %} 
            </div>
            {% ctrl_select "round" "Round" %} <br>
            
            {% ctrl_table "editRnd" %}
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-6">
        <div class="display_block inner_margin1 outer_padding2 frame_admin" style="min-height: 400px;">
            {% ctrl_strong "cfg" "Transform Data" %}
            <div class="display_block">
                {% ctrl_listing "home" "Home" %}
            </div>
            {% ctrl_listing "away" "Away" %}
            
            {% ctrl_table "gameEvents" %}
            
            <div class="display_table">
                <div class="display_row">
                    <div class="display_cellM" style="width: 100%;">
                        {% ctrl_normal "loadmsg" %}
                    </div>
                    <div class="display_cellM">
                        {% ctrl_button "load" "Load Game" %}
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    
</div>


<!-- SCRIPTS -->

<script>

var PLAYERS = [];
var GAMEDATA = {};

$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    {% for ssn in seasons %}
    $('#season_select').append($('<option>', {value : '{{ ssn }}' }).text('{{ ssn }}'));
    {% endfor %}
    
    {% for rnd in rounds %}
    $('#round_select').append($('<option>', {value : '{{ rnd }}' }).text('{{ rnd }}'));
    {% endfor %}
    
    $('#round_select option[value={{ currRnd }}]').attr('selected','selected');
    
    $('#round_select').change(function() {
        RefreshRound();
    });
    
    var fixture = $.parseJSON('{{ fixture | escapejs }}');      cl(fixture);
    SetDeluxeFixtureDetails(fixture);    
    
    PLAYERS = $.parseJSON('{{ players | escapejs }}');
    
    $('#load_button').addClass('format_disable');
    $('#load_button').click(function() {
        LoadGameLive();
    });
    
    //$('#url6909_text').val("http://www.livescores.com/soccer/iran/persian-gulf-league/zob-ahan-vs-gostaresh-foolad-fc/1-2305741/");
    
    $('body').css('cursor', 'default');
});

// DISPLAY FUNCTIONS

function SetDeluxeFixtureDetails(p_fixt)
{               
    var table = $('#editRnd_table').DataTable( {
        data: p_fixt,
        aoColumns: [
            {
                title: "Home",
                mData: "home_club",
                sClass: "format_fixline",
            },
            {
                title: "Away",
                mData: "away_club",
                sClass: "format_fixline",
            },
            {
                title: "Game Over",
                mData: "gameOver",
                sClass: "format_fixline",
                mRender: function (data, type, full) {
                    
                    var js_dt = Date.parseString(full.gameOver.substring(0,16), "yyyy-MM-dd HH:mm");
                    var msg = js_dt.format("MM-dd HH:mm");
                    
                    return msg;
                }   
            },  
            {
                title: "Events",
                mData: "events",
                sClass: "format_center",
            },  
            {   
                title: "LiveScores URL",
                sWidth: "100%",
                sClass: "",
                mRender: function (data, type, full) {
                    var html = '                            \
                        <div class="">                      \
                            <input id="url{0}_text" type="text"  class="format_disable"  \
                                style="width: 96%; box-sizing: border-box; ">  \
                            </input>                        \
                        </div>                              \
                        '.format(full.id); 
                    return html; 
                }   
            },  
            {   
                title: "Extract",
                sClass: "format_center",
                mRender: function (data, type, full) {
                    var html = '                            \
                        <div class="">                      \
                            <input id="import{0}_button" type="button" value="Extract"      \
                                class="format_button format_disable">                      \
                            </input>                        \
                        </div>                              \
                        '.format(full.id); 
                    return html; 
                }   
            },  
            {   
                title: "Delete Events",
                sClass: "format_center",
                mRender: function (data, type, full) {
                    var html = '                            \
                        <div class="">                      \
                            <input id="delete{0}_button" type="button" value="Delete"   \
                                class="format_button format_disable">                   \
                            </input>                        \
                        </div>                              \
                        '.format(full.id); 
                    return html; 
                }   
            },  
        ],  
        bSort: false,
        scrollCollapse: true,
        paging: false,
        bFilter: false,
        bInfo: false,
        bDestroy: true,          
        initComplete: function() {
            PostDraw();
        }
    } );
    
    function PostDraw()
    {        
        $.each(p_fixt, function(idx, game) {
            if (game.events == 0)
            {
                $('#import{0}_button'.format(game.id)).removeClass('format_disable');
                $('#url{0}_text'.format(game.id)).removeClass('format_disable');
                $('#import{0}_button'.format(game.id)).click(function() {
                    var htmlID = $(this).attr('id');        // get the html-id of the calling element
                    var id = htmlID.match(/\d+/)[0];        // get the first number in string
                    ImportGameLive(id);
                });
            }
            else
            {
                $('#delete{0}_button'.format(game.id)).removeClass('format_disable');
                $('#delete{0}_button'.format(game.id)).click(function() {
                    var htmlID = $(this).attr('id');        // get the html-id of the calling element
                    var id = htmlID.match(/\d+/)[0];        // get the first number in string
                    DeleteGameEvents(id);
                });                
            }
        });
    }
    
}

function SetDeluxeGameEvents(p_events)
{               
    var table = $('#gameEvents_table').DataTable( {
        data: p_events,
        aoColumns: [
            {
                title: "Event",
                mData: "event",
                sClass: "format_fixline",
            },
            {
                title: "Time",
                mData: "time",
                sClass: "format_center",
            },
            {
                title: "Club",
                mData: "club",
                sClass: "format_fixline",
            },  
            {
                title: "LiveScore Player",
                mData: "live_player",
                sClass: "format_fixline",
            },  
            {   
                title: "IPLStats Player",
                sWidth: "100%",
                sClass: "",
                mRender: function (data, type, full) {
                    if (full.live_player)
                    {
                        var html = '                        \
                        <div class="">                      \
                            <input id="player{0}_text" type="text" class="format_disable"  \
                                style="width: 96%; box-sizing: border-box;">  \
                            </input>                        \
                        </div>                              \
                        '.format(full.time);
                        return html; 
                    }
                    return "";
                }   
            },  
        ],  
        bSort: false,
        scrollCollapse: true,
        paging: false,
        bFilter: false,
        bInfo: false,
        bDestroy: true,          
        initComplete: function() {
            PostDraw();
        }
    } );
    
    function PostDraw()
    {   
        $.each(p_events, function(idx, event) {
            if (event.ipls_player)
            {
                $('#player{0}_text'.format(event.time)).val(event.ipls_player);
            }
            else
            {
                $('#player{0}_text'.format(event.time)).removeClass('format_disable');
                $('#player{0}_text'.format(event.time)).autocomplete({ source: PLAYERS, minLength: 4 });
            }
        });
    }
}


// AJAX FUNCTIONS


function RefreshRound()
{    
    $('body').css('cursor', 'wait');
    
    var round = $('#round_select option:selected').text();
    
    $.ajax({
        url: '{% url "football:etl_livescores_jx" "refresh_round" %}',
        data: {'round': round, },
        success: function(p_data) {         cl(p_data);
            
            SetDeluxeFixtureDetails(p_data);    
            
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "RefreshRound()", '#import_status');
        },
        complete: function() {
            $('body').css('cursor', 'default');
        }
    });
}


function ImportGameLive(p_id)
{    
    $('body').css('cursor', 'wait');

    var url = $('#url{0}_text'.format(p_id)).val();     //cl(url);
    
    $.ajax({
        //type: 'POST',
        url: '{% url "football:etl_livescores_jx" "preImport_liveGame" %}',
        data: {'gameId': p_id, 'url': url,},
        success: function(p_data) {         //cl(p_data);
            GAMEDATA = p_data;
            $('#home_listing').text(p_data.home);
            $('#away_listing').text(p_data.away);
            SetDeluxeGameEvents(p_data.events);
            $('#load_button').removeClass('format_disable');
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportGameLive()", '#import_status');
        },
        complete: function() {
            $('body').css('cursor', 'default');
        }
    });
}


function DeleteGameEvents(p_id)
{    
    $('body').css('cursor', 'wait');
    
    $.ajax({
        type: 'POST',
        url: '{% url "football:etl_livescores_jx" "delete_gameEvents" %}',
        data: {'gameId': p_id,},
        success: function(p_data) {    // cl(p_data);
            SetDeluxeFixtureDetails(p_data);  
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "DeleteEvents()", '#import_status');
        },
        complete: function() {
            $('body').css('cursor', 'default');
        }
    });
}


function LoadGameLive(p_id)
{    
    $('body').css('cursor', 'wait');
    $('#loadmsg_normal').text("");
    var passed = true;
    
    $.each(GAMEDATA.events, function(idx, event) {
        if (event.live_player)
        {
            var ipls_player = $('#player{0}_text'.format(event.time)).val();
            if (!ipls_player)
            {
                $('#loadmsg_normal').text("IPLS player is missing.");
                passed = false;
                $('body').css('cursor', 'default');
                return false;       // retun false to abort $each iteration
            }
            event.ipls_player = ipls_player;
        }
    });
    
    if (!passed)
        return;
    
    $.ajax({
        type: 'POST',
        url: '{% url "football:etl_livescores_jx" "load_liveGame" %}',
        data: { 'gameData': JSON.stringify(GAMEDATA) },     // json data must be encoded as string
        success: function(p_data) {             //cl(p_data);
            $('#loadmsg_normal').text(p_data);
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "LoadGameLive()", '#import_status');
        },
        complete: function() {
            $('body').css('cursor', 'default');
        }
    });
}


</script>

{% endblock content %}

football/templates/etl_persianleague.html
{% extends "common_base.html" %}
{% load utility_ttags %}

{% block content %}


<div class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_admin">
            <span class="font_title">ETL Persian League</span>
        </div>
    </div>
    <div class="col-xs-12">
        <hr class="format_separator">
    </div>            
</div>


<div class="row">
    
    <div class="col-xs-12">
        <div class="inner_margin1 frame_admin">
            <span class="font_section">Live Fixtures</span>
        </div>
    </div>
    
    <div class="col-sm-12">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_inputText "url" "URL" True %}
            {% ctrl_button "import" "Web Import" %}        
        </div>
    </div>
    
    <div class="col-xs-12">
        <div style="display: none;">{% ctrl_status "liveFixtures" %}</div>
        <hr class="format_separator">
    </div>
    
</div>


<!-- SCRIPTS -->

<script>

var USER = "{{ user }}";

$(document).ready(function()
{      
    $('body').css('cursor', 'wait');
    
    //$('#url_text').val("http://www.persianleague.com/index.php/matchdate?id=39&id2=39&displayresults=yes&badges_ondisplay=yes&venue_id=7");
    
    $("#import_button").click(function() {
        ImportFixture();
    });
    
    
    
    
    
    
    $("body").css("cursor", "default");
});


function DisableForm()
{
    $("#_select").prop("disabled", true);
    $("body").css("cursor", "wait");
}

function EnableForm()
{
    $("#_select").prop("disabled", false);
    $("body").css("cursor", "default");    
}

function ImportFixture()
{    
    $("body").css("cursor", "wait");
    var url = $("#url_text").val();
    $("#liveFixtures_status").html(null);
    
    $.ajax({
        type: 'POST',
        url: '/football/persianleague/import_fixture/',
        data: {'url': url,},
        success: function(p_data) {     cl(p_data);
            
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "ImportFixture()", '#liveFixtures_status');
        },
        complete: function() {
            $("body").css("cursor", "default");
        }
    });
}


</script>

{% endblock content %}