app_proj/urls.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
PROJECT/URLS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

from django.conf.urls import include, url
from django.contrib import admin
import allauth.account.views as AV

import common.views as BV 
import football.views as FV 
import members.views as MV 
import prediction.views as PV 
import central.views as CV


football_url = [
    url(r'^game_ref/$', FV.fb_game, name='fb_game'),
    url(r'^season_ref/$', FV.fb_season, name='fb_season'),
    url(r'^club_ref/$', FV.fb_club, name='fb_club'),
    url(r'^player_ref/$', FV.fb_player, name='fb_player'),
    url(r'^research_jx/([a-zA-Z0-9_]+)/$', FV.research_jx, name='research_jx'),
    
    url(r'^etl_iplstats/$', FV.etl_iplstats, name='etl_iplstats'),
    url(r'^etl_iplstats_jx/([a-zA-Z0-9_]+)/$', FV.etl_iplstats_jx, name='etl_iplstats_jx'),
    
    url(r'^etl_livescores/$', FV.etl_livescores, name='etl_livescores'),
    url(r'^etl_livescores_jx/([a-zA-Z0-9_]+)/$', FV.etl_livescores_jx, name='etl_livescores_jx'),
    
    url(r'^dataManager_jx/([a-zA-Z0-9_]+)/$', FV.dataManager_jx, name='dataManager_jx'),
]


members_url = [    
    url(r"^accounts/signup/$", AV.signup, name="account_signup"),        # must preserve allauth name field for its internal calls
    url(r"^accounts/login/$", AV.login, name="account_login"),
    url(r"^accounts/logout/$", AV.logout, name="account_logout"),
    
    url(r"^accounts/email/$", MV.email, name="account_email"),
    url(r"^accounts/confirm-email/(?P<key>[-:\w]+)/$", AV.confirm_email, name="account_confirm_email"),
    url(r"^accounts/confirm-email/$", AV.email_verification_sent, name="account_email_verification_sent"),    # used when email still requires confirmation
    url(r"^accounts/password/change/$", AV.password_change, name="account_change_password"),
    url(r"^accounts/password/reset/$", MV.password_reset, name="account_reset_password"),
    url(r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$", MV.password_reset_from_key, name="account_reset_password_from_key"),
    url(r"^accounts/inactive/$", AV.account_inactive, name="account_inactive"),        
    
    url(r'^auth_dialog/', MV.dialog),
    url(r'^messages/', MV.messages, name='messages'),
    url(r'^members_admin/', MV.members_admin, name='members_admin'),
    url(r'^contacts/', MV.contacts, name='contacts'),
    url(r'^profile/', MV.profile, name='profile'),
    
    url(r'^db_edit/([a-zA-Z0-9_]+)/$', MV.db_edit),
    url(r'^db_report/([a-zA-Z0-9_]+)/$', MV.db_report),
]


central_url = [
    url(r'^store/$', CV.store, name='store'),
    url(r'^company/$', CV.company, name='company'),
    url(r'^data_master/$', CV.master, name='master'),
    url(r'^view_profile/([a-zA-Z0-9_]+)', CV.view_profile, name='view_profile'),
    url(r'^central_jx/([a-zA-Z0-9_]+)/$', CV.central_jx, name='central_jx'),
    
    url(r'^admin_messages/', CV.admin_messages, name='admin_messages'),
    url(r'^adminMsg_jx/([a-zA-Z0-9_]+)/$', CV.adminMsg_jx, name='adminMsg_jx'),
    
    url(r'^pu_rewards/', CV.pu_rewards, name='pu_rewards'),
    url(r'^pu_rewards_jx/([a-zA-Z0-9_]+)/$', CV.pu_rewards_jx, name='pu_rewards_jx'),
    url(r'^pu_message_test/', CV.pu_message_test, name='pu_message_test'),
    
    url(r'^bot_users/', CV.botUsers, name='botUsers'),
    url(r'^botUsers_jx/([a-zA-Z0-9_]+)/$', CV.botUsers_jx, name='botUsers_jx'),
]


univpred_url = [
    url(r'^universal/upgrades/$', PV.univ_headq, name='univ_headq'),
    url(r'^universal/predictions/$', PV.univ_preds, name='univ_preds'),
    url(r'^universal/standings/$', PV.univ_ranks, name='univ_ranks'),
    url(r'^universal/the_rules/$', PV.univ_rules, name='univ_rules'),
    url(r'^universal_jx/([a-zA-Z0-9_]+)/$', PV.universal_jx, name="universal_jx"),
]


urlpatterns = [
    url(r'^$', CV.landing, name='landing_page'),   
    url(r'^members/', include(members_url)),     # do not use a namespace, breaks allauth reverse urls 
    url(r'^research/', include(football_url, namespace='football')),
    url(r'^prediction/', include(univpred_url, namespace='prediction')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^central/', include(central_url, namespace='central', app_name='central')),       # appname?
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    
    url(r'^', BV.not_found, name='not_found'),
]

central/views.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
CENTRAL/VIEWS.py
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

import json

from django.shortcuts import render
from django.http import JsonResponse
from django.utils.safestring import mark_safe
from django.contrib.auth.decorators import user_passes_test

from django.views.decorators.csrf import csrf_exempt

import common.utility as CU
import football.models.tables as FT
import football.models.football as FM
import football.models.dataManager as FD
import members.models.members as MM
import prediction.models.universal as PU
import central.models.central as CN
import central.models.admin_messages as DM
import central.models.bot_users as BU

import logging
prog_lg = logging.getLogger('progress')
excp_lg = logging.getLogger('exception')


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
CENTRAL PAGES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


def landing(request):    
    season = FM.TimeMachine.GetLastBracket()['season']
    logos = FM.Reports_General.GetClubsTransp(season)
    topRanks = PU.Reporter_Ranks.GetTopRanks()
    
    context = {
        'topRanks': mark_safe(json.dumps(topRanks)),
        'logos': logos,
    }
    return render(request, 'landing_page.html', context)


def store(request):
    storeConfig = CN.Reporter.GetStoreConfig(request.user)
    
    context = {
        'storeConfig': storeConfig,
    }
    return render(request, 'store.html', context)


def company(request):
    context = {
    }
    return render(request, 'company.html', context)


@user_passes_test(lambda u: u.is_superuser)
def master(request):
    sites = CN.Reporter.GetSites()
    seasons = FM.Reports_General.GetSeasons()
    season = seasons[0]
    
    hretRounds = FM.Reports_Admin.GetRoundSummary(season)
    byRound = mark_safe(json.dumps(hretRounds.results))   if not isinstance(hretRounds.results, str)   else None
    
    simTime = FM.TimeMachine.GetSimTime()
    if simTime:
        simTime = simTime.strftime(CU.FORMAT_DTSTR)
    
    context = {
        'msgAdmin': DM.Reporter.GetMessageAdmin(),
        'sites': CN.Reporter.GetSites(),
        'coreSummary': mark_safe(json.dumps(FM.Reports_Admin.GetCoreCounts())),
        'seasonTable': mark_safe(json.dumps(FM.Reports_Admin.GetFullTable(FT.Season))),
        'clubTable': mark_safe(json.dumps(FM.Reports_Admin.GetFullTable(FT.Club))),
        #'eventTable': FM.Reports_Admin.GetFullTable(FT.Event),
        
        'seasons': seasons,
        'seasonSummary': mark_safe(json.dumps(FM.Reports_Admin.GetSeasonSummary())),
        'byRound': byRound,
        
        'simTime': simTime,
    }
    return render(request, 'data_master.html', context)


def view_profile(request, username):
    season = FM.TimeMachine.GetTodaysBracket()['season']
    user_m = MM.Profile_Reporter.GetUserModel(username)
    
    profileData = MM.Profile_Reporter.ViewProfileData(request.user, username)
    puRoster = PU.Reporter.GetUserRoster(user_m, season)
    puAbilsOwned = PU.Reporter.GetAbilitiesOwned(user_m, season)
    puRecord = PU.Reporter.GetRecord(user_m, season)
    
    context = {
        'profileData': profileData,
        'friendList': mark_safe(json.dumps(profileData['friendList'])),
        'puRoster': puRoster,
        'puAbilsOwned': mark_safe(json.dumps(puAbilsOwned)),
        'puRecordAT': mark_safe(json.dumps(puRecord['recordAT'])),
        'puRecordRD': mark_safe(json.dumps(puRecord['recordRD'])),
        'puThresholds': mark_safe(json.dumps(puRecord['thresholds'])),
    }
    return render(request, 'view_profile.html', context)


def central_jx(request, command):
    
    prog_lg.info("ajax command: " + command)
    
    
    if command == 'update_buyDiamonds':
        itemId = request.POST.get('itemId')
        hret = CN.Editor.PurchaseDiamonds(request.user, itemId) 
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'update_exchangeTokens':
        diamonds = int(request.POST.get('diamonds'))
        hret = CN.Editor.ExchangeTokens(request.user, diamonds) 
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    
    elif command == 'create_msgUser':
        hret = DM.Editor.CreateMessageUser()
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'update_sites':
        CN.Editor.InitializeSites()
        siteOne = CN.Reporter.GetSites()
        
        hret = CU.HttpReturn()
        hret.results = {'domain': siteOne.domain, 'name': siteOne.name}
        hret.status = 200        
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    
    elif command == 'update_claimRewards':
        # this is moved from pu_rewards_jx because the users need access
        messageID = request.POST.get('messageID')
        hret = DM.PU_Editor.ClaimRewards(request.user, messageID)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    else:
        msg = "command invalid: " + command
        excp_lg.error(msg)
        return JsonResponse(msg, safe=False, status = 404)  


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
ADMIN MESSAGES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


@user_passes_test(lambda u: u.is_superuser)
def admin_messages(request):
    context = {
        'inbox': mark_safe(json.dumps(DM.Reporter.GetAdminInbox())),
        'messageAdmin': DM.Reporter.GetMessageAdmin(),
        'recTypes': ["To User", "To All Users"],
        'msgReport': mark_safe(json.dumps(DM.Reporter.GetMessageReport())),
    }
    return render(request, 'admin_messages.html', context)


@user_passes_test(lambda u: u.is_superuser)
def adminMsg_jx(request, command):
    
    prog_lg.info("ajax command: " + command)
    
    
    if command == 'get_message':
        msgID = request.GET.get('msgID')
        hret = DM.Reporter.GetAdminMessage(msgID)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'get_convo':
        thdID = request.GET.get('thdID')
        hret = DM.Reporter.GetAdminConvo(thdID)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'delete_conv':
        hret = DM.Editor.DeleteConvo(request)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'insert_newMsg':
        hret = DM.Editor.WriteMessage(request)
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'insert_replyMsg':
        hret = DM.Editor.ReplyMessage(request)    
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'get_inbox':
        inbox = DM.Reporter.GetAdminInbox()   
        hret = CU.HttpReturn()
        hret.results = inbox
        hret.status = 201
        return JsonResponse(hret.results, safe=False, status=hret.status)
        
    elif command == 'delete_messages':
        hret = DM.Editor.DeleteMessages()
        hret.results = DM.Reporter.GetMessageReport()
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    
    else:
        msg = "command invalid: " + command
        excp_lg.error(msg)
        return JsonResponse(msg, safe=False, status = 404)  


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
UNIVERSAL REWARDS
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""


@user_passes_test(lambda u: u.is_superuser)
def pu_rewards(request): 
    seasons = FM.Reports_General.GetSeasons()
    #seasons = ['IPL2014']
    roundList = FM.Reports_General.GetRounds(seasons[0], "lastData")
    
    if roundList:
        try:
            rewardsData = PU.Reporter_Ranks.RunRewardsData(seasons[0], roundList[0])
            status = PU.Reporter_Ranks.GetRewardStatus(seasons[0], roundList[0])
        except:
            rewardsData = "no data"
            status = "no status"
            
    else:
        rewardsData = "no data"
        status = "no status"
    
    context = {
        'seasons': seasons,
        'roundList': roundList,
        
        'charts': mark_safe(json.dumps(rewardsData))   if not isinstance(rewardsData, str)   else None,
        'status': mark_safe(json.dumps(status))   if not isinstance(status, str)   else None,
    }
    return render(request, 'pu_rewards.html', context)


@user_passes_test(lambda u: u.is_superuser)
def pu_rewards_jx(request, command):
    
    prog_lg.info("ajax edit command: " + command)
    
    if command == 'get_pointsDist':
        season = request.GET.get('season')
        roundv = request.GET.get('roundv')
        
        results = PU.Reporter_Ranks.RunRewardsData(season, roundv)
        
        hret = CU.HttpReturn()
        hret.results = results
        hret.status = 201
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'get_rewardStatus':
        season = request.GET.get('season')
        #roundv = request.GET.get('roundv')
        roundList = FM.Reports_General.GetRounds(season, "lastData")
        roundv = roundList[0]   if roundList   else ''
        
        charts = PU.Reporter_Ranks.RunRewardsData(season, roundv)
        status = PU.Reporter_Ranks.GetRewardStatus(season, roundv)
        results = {
            'rounds': roundList,
            'charts': charts,
            'status': status   if status['scoreSummary']   else "No score summary available",
        }
        
        hret = CU.HttpReturn()
        hret.results = results
        hret.status = 201
        return JsonResponse(hret.results, safe=False, status=hret.status)
    
    elif command == 'update_rankRewards':    
        season = request.POST.get('season')
        roundv = request.POST.get('roundv')

central/templates/bot_users.html
{% extends "common_base.html" %}
{% load utility_ttags %}

{% block content %}


<div id="title_section" class="row">
    <div class="col-xs-12 format_center">
        <div class="inner_margin1 frame_admin">
            <span class="font_title">Bot Users</span>
        </div>
    </div>
</div>


<div id="createUsers_section" class="row">

    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_admin" style="margin-right: 0px;">
                        <span class="font_section">Create Users</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_admin format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "create" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-4 col-xl-3">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            <div class="display_table">
                <div class="display_row">
                    {% ctrl_inputText "usersNum" "Number of Users" True %}
                </div>
                <div class="display_row">
                    {% ctrl_select "season" "Season" %}
                </div>               
            </div>
            <div class="format_center">
                {% ctrl_button "create" "Create Users" %} <br><br>
                {% ctrl_button "delete" "Delete Users" %}        
            </div>               
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_listing "usersTotal" "Current Users" %}
            {% ctrl_table "users" %}        
        </div>
    </div>
    
    
</div>


<div id="makePreds_section" class="row">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_admin" style="margin-right: 0px;">
                        <span class="font_section">Make Predictions</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_admin format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "preds" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-7 col-md-6 col-lg-4 col-xl-3">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_select "round" "Round" %}
            <div class="format_center">
                {% ctrl_button "round" "Make Predictions" %}  
            </div>               
        </div>
    </div>
    
    <div class="col-xs-12 col-sm-7 col-md-6 col-lg-5 col-xl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_table "preds" "" "" "Data Summary" %}
        </div>
    </div>
    
    
</div>


<div id="emailTest_section" class="row" style="display: none;">
    
    <div class="col-xs-12">
        <div class="display_table">
            <div class="display_row">
                <div class="display_cellM">
                    <div class="inner_margin1 frame_admin" style="margin-right: 0px;">
                        <span class="font_section">Test Email</span>
                    </div>
                </div>
                <div class="display_cellT" style="width: 100%;">
                    <div class="display_block frame_admin format_separator">
                    </div>
                </div>
            </div>
        </div>
        <div style="display: none;">{% ctrl_status "email" %}</div>
    </div>
    
    <div class="col-xs-12 col-sm-6 col-xl-4">
        <div class="display_block inner_margin1 outer_padding2 frame_admin">
            {% ctrl_inputText "email" "E-mail" True %}
            {% ctrl_button "email" "Send E-mail" %}  
        </div>
    </div>
    
    
</div>


<!-- SCRIPTS -->

<script>
//
// FORM BASICS
//
$(document).ready(function()
{      
    // create users
    
    $('#usersNum_text').val('100');  

    {% for ssn in seasons %}
    $('#season_select').append($('<option>', {value : '{{ ssn }}' }).text('{{ ssn }}'));
    {% endfor %}
    
    $('#season_select').change(function() {
        InitPreds();
    });
    
    $('#create_button').click(function() {
        CreateTestUsers();
    });
    
    $('#delete_button').click(function() {
        DeleteBotUsers();
    });
    
    DisplayTestUserCount();            
    DisplayTestUserDetails();
    
    // make predictions
    
    InitPreds();
    
    $('#round_button').click(function() {
        MakeOneRound();
    });
    
    // test email
    
    $('#email_text').val('liono@hotmail.com');
    
    $('#email_button').click(function() {
        SendTestEmail();
    });

});

function DisableForm()
{
    $("#usersNum_text").prop("disabled", true);
    $("#season_select").prop("disabled", true);
    $("#create_button").prop("disabled", true);
    $("#round_select").prop("disabled", true);
    $("#round_button").prop("disabled", true);
    $("body").css("cursor", "wait");
}

function EnableForm()
{
    $('#usersNum_text').prop('disabled', false);
    $('#season_select').prop('disabled', false);
    $('#create_button').prop('disabled', false);
    $('#round_select').prop('disabled', false);
    $('#round_button').prop('disabled', false);
    $('body').css('cursor', 'default');    
}


//
// BOT USERS
//
function CreateTestUsers()
{
    var userNum = $('#usersNum_text').val();
    var season = $('#season_select option:selected').text();
    $('#usersTotal_listing').val(null);
    $('#create_status').text('');
    DisableForm();
    
    $.ajax({
        type: 'POST',
        url: '{% url "central:botUsers_jx" "create_testUsers" %}',
        data: {'userNum': userNum, 'season': season},
        success: function(p_data) {  
            DisplayTestUserCount();            
            DisplayTestUserDetails();
            DisplayCurrentData();
        },
        error: function(p_err) {  
            ErrorToStatus(p_err.responseText, 'CreateTestUsers()', '#create_status');
        },
        complete: function() {
            EnableForm();    
        }
    });
}

function DisplayTestUserCount()
{
        
    $.ajax({
        type: "GET",
        url: '{% url "central:botUsers_jx" "testUsers_count" %}',
        success: function(p_data) {        cl(p_data);
            $("#usersTotal_listing").text(p_data.userCnt);
        },
        error: function(p_err) {   
            ErrorToStatus(p_err.responseText, 'DisplayTestUserCount()', '#create_status');
        },
        complete: function() {
            EnableForm();    
        }
    });
}

function DisplayTestUserDetails()
{
    $.ajax({
        type: "GET",
        url: '{% url "central:botUsers_jx" "testUsers_details" %}',
        success: function(p_data) {         //cl(p_data);
            if (!p_data || p_data.length == 0)
            {
                $('#users_table').html("Bot data not available.");
            }
            else
            {
                // TODO: update to use colFormat 
                cols = ["Club", "Total", "Slogan", "Icon"]
                recs = []
                $.each(p_data, function(key, value) {
                    newRow = [value.club, value.total, value.slogan, value.icon];
                    recs.push(newRow);
                }); 
                dtable = {'columns': cols, 'records': recs}
                SetDataTable('#users_table', dtable);
            }
        },
        error: function(p_err) {   
            ErrorToStatus(p_err.responseText, 'DisplayTestUserDetails()', '#create_status');
        },
        complete: function() {
            EnableForm();    
        }
    });
}


function DeleteBotUsers()
{
    var userNum = $("#usersNum_text").val();
    var season = $("#season_select option:selected").text();
    $("#usersTotal_listing").val(null);
    $("#create_status").text("");
    DisableForm();
    
    $.ajax({
        type: "POST",
        url: '{% url "central:botUsers_jx" "delete_testUsers" %}',
        data: {'userNum': userNum, 'season': season},
        success: function(p_data) {  
            DisplayTestUserCount();            
            DisplayTestUserDetails();
            DisplayCurrentData();
        },
        error: function(p_err) {  
            ErrorToStatus(p_err.responseText, 'CreateTestUsers()', '#create_status');
        },
        complete: function() {
            EnableForm();    
        }
    });
}


//
// MAKE PREDICTIONS
//
function InitPreds()
{
    var season = $('#season_select option:selected').text();    
    $('#round_select').empty();
    
    $.ajax({    
        url: '{% url "football:research_jx" "rounds" %}',
        data: {'season': season},
        success: function(p_data) {             cl(p_data);
            if (typeof(p_data) == 'string')
                $('#round_select').append($('<option>', {"none" : "none" }).text("none"));
            else 
                $.each(p_data, function(key, value) {
                    $('#round_select').append($('<option>', {value : key }).text(value));
                });
        }, 
        error: function(p_err) {
            ErrorToStatus(p_err.responseText, "InitPreds()", '#preds_status');
        } 
    });
    
    DisplayCurrentData();
}

function MakeOneRound()
{   
    $("#preds_status").text("");
    var season = $("#season_select option:selected").text();
    var round = $("#round_select option:selected").text();
    DisableForm();
    
    $.ajax({
        type: "POST",
        url: '{% url "central:botUsers_jx" "makePreds_testUsers" %}',
        data: {'season': season, 'round': round},
        success: function(p_data) {  
            DisplayCurrentData();  
        }, 
        error: function(p_err) {
            $("#preds_table").html(null);
            DisplayCurrentData();  
            ErrorToStatus(p_err.responseText, 'MakeOneRound()', '#preds_status');
        }, 
        complete: function() {
            EnableForm();    
        }
    });
}

function DisplayCurrentData()
{
    var season = $("#season_select option:selected").text();   
    $("#preds_table").html(null);
    $("#preds_status").html(null);
    
    $.ajax({
        url: '{% url "prediction:universal_jx" "get_fixtSummary" %}',
        data: {'season': season},
        success: function(p_data) {   //cl(p_data);
            if (typeof(p_data) == 'string') {
                $('#preds_table').html(p_data);
            }
            else {
                var fullT = JSONtoFullTable(p_data.data);
                SetDataTable('#preds_table', fullT, p_data.colFormat);
            }
        },  
        error: function(p_err) {   
            ErrorToStatus(p_err.responseText, 'DisplayCurrentData()', '#preds_status');
        }   
    }); 
}   

//
// TEST EMAIL
//
function SendTestEmail()
{
    var email = $('#email_text').val();   
    $('#email_status').html(null);       
    
    $.ajax({
        type: 'post',
        url: '/members/test_email/',
        data: {'email': email},
        success: function(p_data) {     
            $('#email_status').html(p_data);
        },
        error: function(p_err) {   
            ErrorToStatus(p_err.responseText, 'SendTestEmail()', '#email_status');
        } 
    });
}


</script>


{% endblock content %}

central/templates/message_testPage.html
{% load utility_ttags %}
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap: The above 3 meta tags *must* come first in the head -->
    
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <link   href="{% static 'third_party/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'third_party/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
    <link   href="{% static 'third_party/bootstrap-extra/navbar-fixed-side.css' %}" rel="stylesheet">
    <link   href="{% static 'third_party/bootstrap-extra/bootstrap-xl-xxl.css' %}" rel="stylesheet">
    
    <script src="{% static 'third_party/DataTables-1.10.10/media/js/jquery.dataTables.min.js' %}"></script>
    <link   href="{% static 'third_party/DataTables-1.10.10/media/css/jquery.dataTables.min.css' %}" rel="stylesheet" />
    <script src="{% static 'third_party/jquery-ui-1.11.4/jquery-ui.min.js' %}"></script>
    <link   href="{% static 'third_party/jquery-ui-1.11.4/jquery-ui.min.css' %}" rel="stylesheet" />
    <link   href="{% static 'third_party/font-awesome-4.6.3/css/font-awesome.min.css' %}" rel="stylesheet" />
    <script src="{% static 'third_party/JavascriptToolbox/date.js' %}"></script>
    
    <!-- Bootstrap: put custom css after bootstrap.css so custom styles override -->
    <link   href="{% static 'style.css' %}?{% now 'U' %}" rel="stylesheet" /> 
    <script src="{% static 'utility.js' %}?{% now 'U' %}"></script>
    
    <title>Message Test</title>
    
</head>


<body>
    
        <div class="display_table" style="background: white; width: 30%;"> 
            <div class="display_cellM " style="border: 2px solid black;">
                <div class="display_block outer_padding2">
                    <span id="body_normal">
                        
                        {% include "message_puRankRewards.html" %}
                        
                    </span>
                </div>
            </div>
        </div>
        
</body>